<?php

use Phalcon\Mvc\Model;

class Farmers extends Model
{
	public $id;
	public $first_name;
	public $middle_name;
	public $last_name;
	public $birth_date;
	public $pan_number;
	public $aadhar_number;
	public $username;
	public $password_encrypted;

	public static function findFirst( $parameters = NULL ) {
		parent::findFirst( $parameters ); // TODO: Change the autogenerated stub
	}
}