<h2>Sign up / Register</h2>

<?php echo $this->tag->form("signup/register"); ?>

<p>
	<label for="first_name">First Name</label>
	<?php echo $this->tag->textField("first_name"); ?>
</p>
<p>
	<label for="middle_name">Middle Name</label>
	<?php echo $this->tag->textField("middle_name"); ?>
</p>
<p>
	<label for="last_name">Last Name</label>
	<?php echo $this->tag->textField("last_name"); ?>
</p>

<p>
	<label for="username">User Name</label>
	<?php echo $this->tag->textField("username"); ?>
</p>
<p>
	<label for="password">Password</label>
	<?php echo $this->tag->passwordField("password"); ?>
</p>
<p>
	<label for="password_confirm">Confirm Password</label>
	<?php echo $this->tag->passwordField("password_confirm"); ?>
</p>
<p>
	<?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>