<h2>Sign up / Register</h2>

<?php echo $this->tag->form("signup/register"); ?>

<p>
	<label for="FirstName">First Name</label>
	<?php echo $this->tag->textField("FirstName"); ?>
</p>
<p>
	<label for="MiddleName">Middle Name</label>
	<?php echo $this->tag->textField("MiddleName"); ?>
</p>
<p>
	<label for="LastName">Last Name</label>
	<?php echo $this->tag->textField("LastName"); ?>
</p>

<p>
	<label for="Username">User Name</label>
	<?php echo $this->tag->textField("Username"); ?>
</p>
<p>
	<label for="password">Password</label>
	<?php echo $this->tag->passwordField("password"); ?>
</p>
<p>
	<label for="password_confirm">Confirm Password</label>
	<?php echo $this->tag->passwordField("password_confirm"); ?>
</p>
<p>
	<?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>